services:
  mongodb:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: password

  minio:
    image: quay.io/minio/minio:latest
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: dev
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000"
      - "9001:9001"

  dagster:
    build:
      context: .
      dockerfile: ./Dockerfile_dagster
    image: kestra/dagster:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
