FROM python:3.12-slim-trixie

# The installer requires curl (and certificates) to download the release archive
RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates

# Download the latest installer
ADD https://astral.sh/uv/install.sh /uv-installer.sh

# Run the installer then remove it
RUN sh /uv-installer.sh && rm /uv-installer.sh

# Ensure the installed binary is on the `PATH`
ENV PATH="/root/.local/bin/:$PATH"

ENV DAGSTER_HOME=/legora
RUN mkdir $DAGSTER_HOME
WORKDIR $DAGSTER_HOME

COPY src $DAGSTER_HOME/src
COPY pyproject.toml $DAGSTER_HOME

RUN uv sync --all-groups

CMD ["uv", "run", "dg", "dev", "-h", "0.0.0.0", "-p", "3000"]
